spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.28.160.1:8082/realms/vk-spring24v1
      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: NtOzpomYMzJSGnt4KnXVUcILksTmDzVB
          discovery:
            provider: keycloak
            authorization-grant-type: client_credentials
            scope:
              - discovery
            client-id: admin-service
            client-secret: NtOzpomYMzJSGnt4KnXVUcILksTmDzVB
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: NtOzpomYMzJSGnt4KnXVUcILksTmDzVB
        provider:
          keycloak:
            issuer-uri: http://172.28.160.1:8082/realms/vk-spring24v1
eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 1
    register-with-eureka: false
    service-url:
      defaultZone: http://172.28.160.1:8761/eureka/