eureka:
  instance:
    hostname: 172.28.160.1
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
  client:
    registryFetchIntervalSeconds: 1
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: eureka-server
            client-secret: te7lbHeqIaIQNglItMVPATmD0Qon1KKY
            scope:
              - openid
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: http://172.28.160.1:8082/realms/vk-spring24v1
      resourceserver:
        jwt:
          issuer-uri: http://172.28.160.1:8082/realms/vk-spring24v1